[project]
name = "coeffe-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.49.1",
]

[tool.uv.workspace]
members = [
    "coeffe-streamlit",
]
